baseurl = "https://belajarperhotelan.eu.org/"
title = "belajar perhotelan"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
# googleAnalytics = "" # Enable Google Analytics by entering your tracking id

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[Author] # Used in authorbox
  name = "Belajar Perhotelan"
  bio = "Penulis"
  avatar = "https://i.ibb.co/F0zbyrb/IMG-20200318-075012.jpg"
[menu]  
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "FnB"
    name = "Fnb"
    url = "/categories/food-and-beverage/"
    weight = 2
  [[menu.main]]
    identifier = "Food and Beverage"
    name = "Food and Beverage"
    url = "/tags/pengertian-food-and-beverage/"
    weight = 3

[Params]
  subtitle = "Belajar Perhotelan • Food and Beverage Service • Banqet • Housekeeping • Front Office • Laundry Perhotelan • Marketing Perhotelan" # Subtitle of your site. Used in site header
  description = "Hanya sebuah blog random." # Site description. Used in meta description
  copyright = "Perhotelan" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02-01-2006" # Change the format of dates
  mathjax = false # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = ""
  # twitter = ""
  # instagram = ""
  # linkedin = ""
  # telegram = ""
  # github = ""
  # gitlab = ""
  # bitbucket = ""
  # email = "belajarperhotelaneuorg@gmail.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Portofolio"
  url = "https://belajarperhotelan.eu.org/hug"
  icon = "svg/instagram.svg" # Optional. Path relative to "layouts/partials"

# [[Params.widgets.social.custom]]
  # title = "My Home Page"
  # url = "http://example.com"

[outputs]
  home = ['html', 'rss', 'json']

